### ISSUE TITLE
Page chrashes when switching datasets after adding filter in CLIENTFS

### ISSUE THREAD

**Issue by henrikaskj** [SemanticComputing/sampo-ui#25]
`TypeError: Cannot read property 'filter' of null`

How to reproduce:
1. Search for a place name
2. Add search filter
3. Add or remove dataset in DatasetSelector

**Comment by esikkala** [comment]
Closed with https://github.com/SemanticComputing/sampo-ui/commit/fd2feebf304e5ae6123b4bbe55bd05d1d9a09cc6
