### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by ivanbacher** [SemanticComputing/sampo-ui#56]
Hello,

Impressive project! I'm interested in its current status.

Are there any upcoming upgrades or a roadmap outlining future developments?
Is there an active development team, and if so, how extensive is it?
Are there considerations for updating outdated dependencies?

Appreciate your insights.

Thank you.

**Comment by HeikkiR** [comment]
Hello And thanks for the interest!

The project is maintained by the Semantic Computing Research Group (SeCo) of Aalto University and University of Helsinki. We have a small team of couple of persons that work with Sampo-UI when we have time from writing our phd theses and other stuff. We generally create new features when our research projects that use Sampo-UI have need for them. Likely the biggest thing currently is that we are in process of updating the dependencies and moving to use Node.js 18. We hope to have the Node upgrade done before the end of this year.

**Comment by ivanbacher** [comment]
That's great! Thank you for the quick response.
