### ISSUE TITLE
Does id on entry need to be in a specific format for dataProviderUrl to generate correct url for instance pages?

### ISSUE THREAD

**Issue by ivanbacher** [SemanticComputing/sampo-ui#57]
Hi,

![Screenshot 2023-12-08 at 10 11 23](https://github.com/SemanticComputing/sampo-ui/assets/5493114/0c1ea197-5964-4485-b7bb-311bb7e1f189)

In the demo app the `dataProviderUrl` for a place in [perspective3](https://sampo-ui.demo.seco.cs.aalto.fi/en/perspective3/faceted-search) is extracted like this in the SPARQL Query:

```
BIND(CONCAT("/places/page/", REPLACE(STR(?place__id), "^.*\\\\/(.+)", "$1")) AS ?place__dataProviderUrl)
```

Which then gets converted to this url: `https://sampo-ui.demo.seco.cs.aalto.fi/en/places/page/tgn_7009504/` to get to the place instance page.

The url of the place entity looks like this: `http://ldf.fi/mmm/place/tgn_7009504`

A place entity in our KG looks like this: `https://.../place/England/Winchester`

The main difference being that the `id` of the entity has two components `England/Winchester` instead of one `tgn_7009504`.

It seems that sampo-ui is removing one of these `id's` e.g  `places/page/England/Abingdon` becomes `places/page/Abingdon`, hence when clicking on the generated link, the `place` instance page cannot find any data, as it is using the incorrect id. E.g. this error message pops up: No data found for id: Abingdon -> (the id should be England/Abingdon).

Any thoughts? How can we get this to work?

Thanks

**Comment by ivanbacher** [comment]
Thank you very much for the quick response. I have updated the query with the new regex. 

![Screenshot 2023-12-08 at 12 22 31](https://github.com/SemanticComputing/sampo-ui/assets/5493114/444eff82-6568-44e8-a466-501d65fe7747)

The link (as shown in the image) is now correct. However, if we click on this link to navigate to the instance page the url is automatically changed to `http://localhost:8080/en/places/page/[local ID part 1]`, somehow the `[local ID part 2]` is removed. 

E.g.  `http://localhost:8080/places/page/England/Canterbury` is changed to `http://localhost:8080/places/page/England`

**Comment by annasahola** [comment]
My bad, the current way URLs are parsed in Sampo-UI doesn't work with local IDs with unencoded slashes. There are at least two ways you could pretty easily get around this: You could encode the local ID part in the SPARQL query with ENCODE_FOR_URI `ENCODE_FOR_URI(REPLACE(...))` and then decode it in the function that handles URI formation from local IDs by using `decodeURIComponent` for localID here: https://github.com/SemanticComputing/sampo-ui/blob/3c3de7c44ca4829f20193f9e8170d32e099cf22b/src/client/helpers/helpers.js#L203


Another option would be to use the whole encoded URI as the local ID by defining the `localIDAsURI` configuration option as true inside the place perspective's [`instanceConfig` object](https://github.com/SemanticComputing/sampo-ui/blob/3c3de7c44ca4829f20193f9e8170d32e099cf22b/src/configs/sampo/search_perspectives/perspective3.json#L31-L48) by adding
`"localIDAsURI": true`
and encoding the whole ID as the local ID in the SPARQL query:
`BIND(CONCAT("/places/page/", ENCODE_FOR_URI(STR(?place__id))) AS ?place__dataProviderUrl)`
